name: isar_generator
description: Code generator for the Isar Database. Finds classes annotated with @Collection.
version: 3.1.8
repository: https://github.com/isar-community/isar
homepage: https://isar.dev
publish_to: https://pub.isar-community.dev/

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  analyzer: ^7.0.0
  build: ^2.3.0
  dart_style: ^3.0.1
  dartx: ^1.1.0
  glob: ^2.0.2
  isar: 
    version: 3.1.8
    hosted: https://pub.isar-community.dev
  path: ^1.8.1
  source_gen: ^2.0.0
  xxh3: ^1.0.1

dev_dependencies:
  build_test: ^2.1.5
  matcher: ^0.12.12
  test: ^1.21.0
  very_good_analysis: ^3.0.1
